config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resource :user
  resource :movie
  resource :movie_reservation

  get 'movies', to: 'movies#index'
  get 'users', to: 'users#index'
  get 'movie_reservations', to: 'movie_reservations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates_presence_of :name, :description
end

app/models/movie_function.rb
class MovieFunction < ApplicationRecord
  validates_presence_of :available_chairs 
end

app/models/movie_reservation.rb
class MovieReservation < ApplicationRecord
  belongs_to :user
  belongs_to :movie

end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :first_name, :international_id, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all
    respond_to do |format|
      format.html
      format.json { render json: @movies }
    end
  end
end

app/controllers/movie_reservations_controller.rb
class MovieReservationsController < ApplicationController
  def new
    @movie_reservation = MovieReservation.new()
  end

  def create
    MovieReservation.create(movie: Movie.find(params[:movie_id]), user: User.find_by(international_id: params[:cedula]))
  end

  def index
    @movie_reservations = MovieReservation.all
    respond_to do |format|
      format.html
      format.json { render json: @movie_reservations }
    end
  end

  def show
    @movie_reservation = MovieReservation.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @movie = Movie.new(params)
  end

  def create
    Movie.create(movie_params)
  end

  def index
    @movies = Movie.all
    respond_to do |format|
      format.html
      format.json { render json: @movies }
    end
  end

  def destroy
    Movie.destroy(params[:id])
  end

  def update
    movie = Movie.find(params[id])
    movie.update(movie_params)
  end

  private

  def movie_params
    params.require(:movie).permit(:id, :name, :description, :image_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @user = User.new(params)
  end

  def create
    User.create(user_params)
  end

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end


  def destroy
    User.destroy(params[:id])
  end

  def update
    user = User.find(params[id])
    user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :phone, :email, :international_id)
  end
end

app/views/home/index.haml
.title-bar.hide-for-large
  .title-bar-left
    %button.menu-icon{"data-open" => "my-info", :type => "button"}
    %span.title-bar-title Lista Películas
.header-movies
  = react_component('Button', { }, prerender: true)
.row.small-up-2.medium-up-3.large-up-4
  - @movies.all.each do |movie|
    .column
      = link_to new_movie_reservation_path(movie_id: movie.id) do
        %img.thumbnail{:src => movie.image_url}/
      %h5= movie.name

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_pack_tag 'application'
    = csrf_meta_tag

  %body
    .off-canvas-wrapper
      .off-canvas-wrapper-inner{"data-off-canvas-wrapper" => ""}
        = render '/shared/menu'
        .off-canvas-content{"data-off-canvas-content" => ""}
          = yield

app/views/movie_reservations/index.html.haml
%section.container
  %h1="Reservaciones"
  .row.small-up-2.medium-up-3.large-up-4
    - @movie_reservations.all.each do |reservation|
      .column
        %h5= reservation.movie.name
        %h5= reservation.user.first_name
        %h5= reservation.user.international_id
        %h5= reservation.created_at

app/views/movie_reservations/new.html.haml
%section.container
  %h1="Reservacion"
  = form_for :movie_reservation, url: {controller: 'movie_reservations', action: 'create'} do |f|
    = hidden_field_tag :movie_id, params['movie_id']
    = text_field_tag "cedula"
    = submit_tag "Create"

app/views/movie_reservations/show.html.haml
%section.container
  %h1="Reservas"

app/views/movies/index.html.haml
%section
  %h1 Listado de peliculas registradas
  = react_component('ListMovies', { movies: @movies, url: movie_path }, prerender: true)

app/views/shared/_menu.haml
#my-info.off-canvas.position-left.reveal-for-large{"data-off-canvas" => "", "data-position" => "left"}
  .row.column
    %br/
    %h1.title= "Placeit"
    .menu
      %ul.nav
        %li
          = link_to 'Reservas', 'movie_reservations#index'
        %li
          = link_to 'Home', root_path
        %li
          = link_to 'Peliculas', 'movies#index'
        %li
          = link_to 'Usuarios', 'users#index'

app/views/users/index.html.haml
%section
  %h1 Listado de usuarios registradas
  = react_component('ListUsers', { users: @users, url: user_path }, prerender: true)